apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: integration-suite-test-component-git-source-brfe
  namespace: integration-e2e-wwjo
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        appstudio.openshift.io/application: integ-app-rgzz
        appstudio.openshift.io/component: integration-suite-test-component-git-source-brfe
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: integration-suite-test-component-git-source-brfe-
      labels:
        appstudio.openshift.io/application: integ-app-rgzz
        appstudio.openshift.io/component: integration-suite-test-component-git-source-brfe
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: integration-e2e-wwjo
    spec:
      params:
      - name: git-url
        value: https://github.com/redhat-appstudio-qe/devfile-sample-python-basic
      - name: output-image
        value: quay.io/psturc/test-images:26d60f5be5ac40c5baa9077e8142443f-$(tt.params.git-revision)
      - name: dockerfile
        value: docker/Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:13f5d9c921b3f727684a00084037f673a0dc4273
        name: docker-build
      workspaces:
      - name: workspace
        volumeClaimTemplate:
          metadata:
            creationTimestamp: null
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
          status: {}
    status: {}
status: {}
